config/routes.rb
Travelportal::Application.routes.draw do

  mount RedactorRails::Engine => '/redactor_rails'

  get "admin/index"

  authenticated :user do
    root :to => 'home#index'
  end

  root :to => 'home#index'

  devise_for :users

  resources :users

  resources :activities

  resources :experiences

  

end

app/models/experience.rb
class Experience < ActiveRecord::Base
  attr_accessible :title, :body, :description, :primary_image

  #has_many :exprelationships, foreign_key:"experience_id", dependent: :destroy
 # has_many :child_experiences, through: :exprelationships, source: :child_experience
  validates :title, :description, :primary_image, presence: true
  validates :title, uniqueness: true
  validates :primary_image, allow_blank: true, format: {
      with: %r{\.(gif|jpg|png)\Z}i,
      message: 'must be a URL for GIF, JPG or PNG image.'}


  def addChild!(other_experience)
    exprelationships.create!(child_id: other_experience.id)
  end
end

app/controllers/experiences_controller.rb
class ExperiencesController < ApplicationController
  # GET /experiences
  # GET /experiences.json
  def index
    authorize! :index, @user, :message => 'Not authorized as an administrator.'
    @experiences = Experience.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @experiences }
    end
  end

  # GET /experiences/1
  # GET /experiences/1.json
  def show
    @experience = Experience.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @experience }
    end
  end

  # GET /experiences/new
  # GET /experiences/new.json
  def new
    authorize! :index, @user, :message => 'Not authorized as an administrator.'
    @experience = Experience.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @experience }
    end
  end

  # GET /experiences/1/edit
  def edit
    authorize! :index, @user, :message => 'Not authorized as an administrator.'
    @experience = Experience.find(params[:id])
  end

  # POST /experiences
  # POST /experiences.json
  def create
    authorize! :index, @user, :message => 'Not authorized as an administrator.'
    @experience = Experience.new(params[:experience])

    respond_to do |format|
      if @experience.save
        format.html { redirect_to @experience, notice: 'Experience was successfully created.' }
        format.json { render json: @experience, status: :created, location: @experience }
      else
        format.html { render action: "new" }
        format.json { render json: @experience.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /experiences/1
  # PUT /experiences/1.json
  def update
    authorize! :index, @user, :message => 'Not authorized as an administrator.'
    @experience = Experience.find(params[:id])

    respond_to do |format|
      if @experience.update_attributes(params[:experience])
        format.html { redirect_to @experience, notice: 'Experience was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @experience.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /experiences/1
  # DELETE /experiences/1.json
  def destroy
    authorize! :index, @user, :message => 'Not authorized as an administrator.'
    @experience = Experience.find(params[:id])
    @experience.destroy

    respond_to do |format|
      format.html { redirect_to experiences_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/experiences_helper.rb
module ExperiencesHelper
end

app/views/experiences/_form.html.erb
<%= form_for(@experience) do |f| %>
  <% if @experience.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@experience.errors.count, "error") %> prohibited this experience from being saved:</h2>

      <ul>
      <% @experience.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description, {:class => "redactor"} %>
  </div>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body, {:class => "redactor"} %>
  </div>

    <div class="field">
      <%= f.label :primary_image %><br />
      <%= f.text_field :primary_image %>
    </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/experiences/edit.html.haml
%h1 Editing experience
%div
  = link_to "Show", @experience
  = link_to "Back", experiences_path
= render 'form'

app/views/experiences/index.html.erb
<h1>Listing experiences</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <!-- <th>Image</th> -->
      <th>Title</th>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody>
  <% @experiences.each do |experience| %>
    <tr class="<%= cycle('list_line_odd','list_line_even') %>">
      <!-- <td><%= image_tag(experience.primary_image, class: 'list_image') %></td> -->
      <td>
        <div><%= link_to experience.title, experience %></div>
        <div><%= experience.description %></div>
      </td>
      <td>
        <ul class="nav nav-pills">
          <li>
            <%= link_to 'Edit', edit_experience_path(experience) %>
          </li>
          <li>
            <%= link_to 'Destroy', experience, method: :delete, data: { confirm: 'Are you sure?' } %>
          </li>
        </ul>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

<br />

<%= link_to 'New Experience', new_experience_path %>

app/views/experiences/new.html.erb
<h1>New experience</h1>

<%= render 'form' %>

<%= link_to 'Back', experiences_path %>

app/views/experiences/show.html.haml
-# Contains the following sections
-# breadcrumbs - show where the user is right now TODO: may be this will be refactored into a common helper
.header
	%h1= @experience.title
.breadcrumbs
	<a href="#">Home</a> › <a href="#">Destination</a> › 
	= @experience.title
.description
	= @experience.description.html_safe
.inner-content
	= @experience.body.html_safe
.experience-main-media
	= link_to image_tag(@experience.primary_image, :border=>0, :size=> "1200x500"), :class => 'featurette-image pull-right'
-#= link_to 'Edit', edit_experience_path(@experience) |
-#link_to 'Back', experiences_path %>

app/views/experiences/show_bak.html.erb
<%#
 Contains the following sections
 * breadcrumbs - show where the user is right now TODO: may be this will be refactored into a common helper
 %>
<div class="header">
  <h1><%= @experience.title %></h1>
</div>
<div class="breadcrumbs">
  <a href="#">Home</a> › <a href="#">Destination</a> › <%= @experience.title %>
</div>
<div class="description">
  <%= @experience.description.html_safe %>
</div>
<div class="inner-content">
  <%= @experience.body.html_safe %>
</div>
<div class="experience-main-media">
  <%= link_to image_tag(@experience.primary_image, :border=>0, :size=> "1200x500"), :class => 'featurette-image pull-right' %>
</div>

<%= link_to 'Edit', edit_experience_path(@experience) %> |
<%= link_to 'Back', experiences_path %>