config/routes.rb
Travelportal::Application.routes.draw do

  mount RedactorRails::Engine => '/redactor_rails'

  get "admin/index"

  authenticated :user do
    root :to => 'home#index'
  end

  root :to => 'home#index'

  devise_for :users

  resources :users

  resources :activities

  resources :experiences

  

end

app/models/activity.rb
class Activity < ActiveRecord::Base
  attr_accessible :title, :body, :description, :inSeason, :price

end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  # GET /activities
  # GET /activities.json
  def index
    @activities = Activity.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @activities }
    end
  end

  # GET /activities/1
  # GET /activities/1.json
  def show
    @activity = Activity.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @activity }
    end
  end

  # GET /activities/new
  # GET /activities/new.json
  def new
    @activity = Activity.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @activity }
    end
  end

  # GET /activities/1/edit
  def edit
    @activity = Activity.find(params[:id])
  end

  # POST /activities
  # POST /activities.json
  def create
    @activity = Activity.new(params[:activity])

    respond_to do |format|
      if @activity.save
        format.html { redirect_to @activity, notice: 'Activity was successfully created.' }
        format.json { render json: @activity, status: :created, location: @activity }
      else
        format.html { render action: "new" }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /activities/1
  # PUT /activities/1.json
  def update
    @activity = Activity.find(params[:id])

    respond_to do |format|
      if @activity.update_attributes(params[:activity])
        format.html { redirect_to @activity, notice: 'Activity was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /activities/1
  # DELETE /activities/1.json
  def destroy
    @activity = Activity.find(params[:id])
    @activity.destroy

    respond_to do |format|
      format.html { redirect_to activities_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/views/activities/_form.html.erb
<%= form_for(@activity) do |f| %>
  <% if @activity.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@activity.errors.count, "error") %> prohibited this activity from being saved:</h2>

      <ul>
      <% @activity.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div class="field">
      <%= f.label :title %><br />
      <%= f.text_field :title %>
    </div>

  <div class="field">
    <%= f.label :inSeason %><br />
    <%= f.text_field :inSeason %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/activities/edit.html.erb
<h1>Editing activity</h1>

<%= render 'form' %>

<%= link_to 'Show', @activity %> |
<%= link_to 'Back', activities_path %>

app/views/activities/index.html.erb
<h1>Listing activities</h1>

<table>
  <tr>
    <th>title</th>
    <th>Inseason</th>
    <th>Price</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @activities.each do |activity| %>
  <tr>
    <td><%= activity.title %></td>
    <td><%= activity.inSeason %></td>
    <td><%= activity.price %></td>
    <td><%= link_to 'Show', activity %></td>
    <td><%= link_to 'Edit', edit_activity_path(activity) %></td>
    <td><%= link_to 'Destroy', activity, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Activity', new_activity_path %>

app/views/activities/new.html.erb
<h1>New activity</h1>

<%= render 'form' %>

<%= link_to 'Back', activities_path %>

app/views/activities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @activity.title %>
</p>
<p>
  <b>Body:</b>
  <%= @activity.body %>
</p>
<p>
  <b>Inseason:</b>
  <%= @activity.inSeason %>
</p>

<p>
  <b>Price:</b>
  <%= @activity.price %>
</p>


<%= link_to 'Edit', edit_activity_path(@activity) %> |
<%= link_to 'Back', activities_path %>